### ISSUE TITLE
`post_save` signal does not get disconnected when class gets unreferenced

### ISSUE THREAD

**Issue by sjoerdjob** [romgar/django-dirtyfields#233]
**Describe the bug**
While running Django migrations, it can happen that subclasses of `DirtyFieldsMixin` get created (and later unreferenced, and thus destroyed). When a class gets unreferenced, the location that class holds in memory gets cleared up again, and a new Python object could be instantiated in that location. That new Python object might be another model class.

**To Reproduce**

See the attached project for a minimal example.
Running `python manage.py migrate` (after having installed the latest version of Django and django-dirtyfields) triggers the issue most of the time.

[minimal.tar.gz](https://github.com/user-attachments/files/17819472/minimal.tar.gz)

**Expected behavior**
Migrations always run completely pass.

**Actual Behavior**
```
Traceback (most recent call last):
  File "/home/sjoerdjobpostmus/dev/minimal/./manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "/home/sjoerdjobpostmus/dev/minimal/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/core/management/commands/migrate.py", line 357, in handle
    post_migrate_state = executor.migrate(
        targets,
    ...<3 lines>...
        fake_initial=fake_initial,
    )
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
        state, plan, full_plan, fake=fake, fake_initial=fake_initial
    )
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
        state, migration, fake=fake, fake_initial=fake_initial
    )
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.app_label, schema_editor, old_state, project_state
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/db/migrations/operations/special.py", line 196, in database_forwards
    self.code(from_state.apps, schema_editor)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjoerdjobpostmus/dev/minimal/stress/migrations/0002_auto_20241119_1734.py", line 28, in update_withoutdirty_instance
    inst.save()
    ~~~~~~~~~^^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/db/models/base.py", line 1012, in save_base
    post_save.send(
    ~~~~~~~~~~~~~~^
        sender=origin,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        using=using,
        ^^^^^^^^^^^^
    )
    ^
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/sjoerdjobpostmus/.virtualenvs/minimal/lib/python3.13/site-packages/dirtyfields/dirtyfields.py", line 172, in reset_state
    new_state = instance._as_dict(check_relationship=True)
                ^^^^^^^^^^^^^^^^^
AttributeError: 'WithoutDirty' object has no attribute '_as_dict'
```

**Environment (please complete the following information):**
 - OS: Debian (but also noticed under Ubuntu)
 - Python version: 3.12 and 3.13.
 - Django version: 4.2+
 - django-dirtyfields version: 1.9.5 and newer.
 
 **Additional context**

A related Django issue is https://code.djangoproject.com/ticket/35801#comment:6 . I'm not sure if either of the codebases can fix this bug separately though, or whether it requires changes in both projects.

Suggested improvements:
* add a class-attribute `registered_post_save_signal` (or something) to make sure `post_save.connect` is only called once per model class.
* In the code that is calling `post_save.connect`, also add 'something' that makes sure that `post_save.disconnect(reset_state, sender=self.__class__, dispatch_uid=...)` gets called whenever the model **class** (not instance) gets unreferenced.

**Comment by sjoerdjob** [comment]
After considering the above a bit more, I think a different route might also be taken.

Instead of registering `reset_state` per class, how about globally connecting to `reset_state` and `m2m_changed` with `sender=None`, and then augment `reset_state` as follows:

```
def reset_state(sender, instance, **kwargs):
    if not isinstance(instance, DirtyFieldsMixin):
        return
```

There are upsides and downsides to this approach.

* Upside: the number of listeners to `post_save` and `m2m_changed` is reduced from arbitrarily many to just 1. This could theoretically result in a minor performance gain on `.save()`, as there are less receivers to be checked.
* Upside: a simple `ModelClass()` will not trigger the 'connect' flow right now, so should become a lot faster.
* Downside: for classes that don't extend `DirtyFieldsMixin`, a call to `reset_state(...)` will now be done, making `.save()` a little bit slower for model instances that are not compatible with `DirtyFieldsMixin`.

The performance characteristics of this change would heavily depend on which model types get the most `.save()` calls. If a flow is heavy in `.save()` calls on `DirtyFieldsMixin` instances, a performance increase would likely be the result. If a flow is heavy in `.save()` calls on non-`DirtyFieldsMixin` instances, a performance loss would likely be the result.

Since the connect has always been in `__init__` since one of the first commits (https://github.com/romgar/django-dirtyfields/commit/df8aa4303cd88652df84a2f1ceae032cf2e061dd#diff-3d39ad67eacb5d622dfbde83549c6d3d81eb3984047284ddf34219ebeeb1e06fR7), I find it hard to evaluate whether a benchmark has been done before deciding this route.
